version: "3"
services:
  mdc:
    image: mdc:local
    build: .
    volumes:
      - ./config.ini:/app/config.ini
      - ../javdb.json:/app/javdb.json
      - ${source_folder}:/app/data
      - ${JAV_output}:/app/JAV_output
    entrypoint: "./docker-entrypoint.sh"
    security_opt:
      - "label:disable"